#!/bin/bash

set -e

version_from_tags() {
  git tag | sort -r | head -1 | sed -e 's/^v//' -e 's/\-.\+//' | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'
}

if echo $CI_COMMIT_REF_NAME | grep -Pq '^release/([\d.]+)$'; then
  RELEASE_BRANCH=1
fi

if [ -n "$RELEASE_BRANCH" ]; then
  RELEASE_VERSION=$(echo "$CI_COMMIT_REF_NAME" | sed 's!release/!!');
else
  RELEASE_VERSION="$(version_from_tags)"
fi

echo "$RELEASE_VERSION"
