FROM kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
      apt-get -y install vim build-essential devscripts equivs

# Install build-deps for the package.
COPY ./debian/control /tmp
RUN apt-get update && echo YYY | mk-build-deps --install --remove /tmp/control

ARG L_UID
RUN useradd -m docker -u $L_UID

USER docker
